---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountms
  template:
    metadata:
      labels:
        app: accountms
    spec:
      imagePullSecrets:
      - name: account
      containers:
      - name: accountms-container
        image: accountmicroacr.azurecr.io/accountms:latest
        imagePullPolicy: Always
        env:
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: accountms