---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trans-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transms
  template:
    metadata:
      labels:
        app: transms
    spec:
      imagePullSecrets:
      - name: transaction
      containers:
      - name: transms-container
        image: accountmicroacr.azurecr.io/transms:latest
        imagePullPolicy: Always
        env:
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: trans-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: transms