---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authms
  template:
    metadata:
      labels:
        app: authms
    spec:
      imagePullSecrets:
      - name: priyachandrima
      containers:
      - name: authms-container
        image: Theerthacustomeracr.azurecr.io/authenticatemicroservices:latest
        imagePullPolicy: Always
        env:
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: authms